import { layerTypes } from '../../types'
export default [
  { layer: 0,
    type: layerTypes.FLOOR,
    body: 
    [ "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     "
    ]
  },
  { layer: 1,
    type: layerTypes.PRIMARY,
    body: 
    [ "=====================================",
      "=                                   =",
      "= =======                           =",
      "= =     E                           =",
      "= =     =           ===========     =",
      "= =     =           =         =     =",
      "= =     =           =         =     =",
      "=                   =         =     =",
      "=                   =         =     =",
      "=                           E =     =",
      "=                   ===========     =",
      "=                                   =",
      "=                                   =",
      "=     O                             =",
      "=                                   =",
      "=                                   =",
      "====================================="
    ]
  },
  { layer: 2,
    type: layerTypes.PRIMARY,
    body: 
    [ "                                     ",
      "                                     ",
      "  XXXXXXX                            ",
      "  XXXXXXX                            ",
      "  XXXXXXX                            ",
      "  XXXXXXXXXXXXXXXXXXXXXXXXXXXX       ",
      "                    XXXXXXXXXX       ",
      "                    XXXXXXXXXX       ",
      "                    XXXXXXXXXX       ",
      "                    XXXXXXX XX       ",
      "                    XXXXXXXXXX       ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     "
    ]
  },
  { layer: 2,
    type: layerTypes.PRIMARY,
    body: 
    [ "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                    ===========      ",
      "                              =      ",
      "         ============         =      ",
      "                    =         =      ",
      "                    =         =      ",
      "                    =         =      ",
      "                    ===========      ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     "
    ]
  },  { layer: 4,
    type: layerTypes.PRIMARY,
    body: 
    [ "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     "
    ]
  }
]
