import { layerTypes } from '../../types'
export default [
  { layer: 0,
    type: layerTypes.FLOOR,
    body: 
    [ "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     "
    ]
  },
  { layer: 1,
    type: layerTypes.PRIMARY,
    body: 
    [ "=====================================",
      "=                                   =",
      "= =======                           =",
      "= =     E                           =",
      "= =     =                           =",
      "= =     =                           =",
      "=                                   =",
      "=                                   =",
      "=                                   =",
      "=                                   =",
      "=                                   =",
      "=                                   =",
      "=                                   =",
      "=                                   =",
      "=                                   =",
      "=                                   =",
      "====================================="
    ]
  },
  { layer: 2,
    type: layerTypes.PRIMARY,
    body: 
    [ "                                     ",
      "                                     ",
      "  XXXXXXX                            ",
      "  XXXXXXX                            ",
      "  XXXXXXX                            ",
      "  XXXXXXX                            ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     "
    ]
  },
  { layer: 3,
    type: layerTypes.PRIMARY,
    body: 
    [ "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     "
    ]
  },
  { layer: 4,
    type: layerTypes.PRIMARY,
    body: 
    [ "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     "
    ]
  }
]
