import { layerTypes } from '../../types'
export default [
  { id: 0,
    type: layerTypes.FLOOR,
    body: 
    [ "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X M M M X X X X X X X X X X X X X X ",
      "                                     ",
      " X M M M X X X X X X M M M M M X X X ",
      "                                     ",
      " X X X X X X X X X X M M M M M X X X ",
      "                                     ",
      " X X X X X X X X X X M M M M M X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     ",
      " X X X X X X X X X X X X X X X X X X ",
      "                                     "
    ]
  },
  { id: 1,
    type: layerTypes.PRIMARY,
    body: 
    [ "=====================================",
      "=                                   =",
      "= =======                           =",
      "= =     E                           =",
      "= =     =           ===========     =",
      "= =     =           =         =     =",
      "=                   =         =     =",
      "=                   =         =     =",
      "=                             =     =",
      "=            T              E =     =",
      "=                    ==========     =",
      "=                                   =",
      "=                                   =",
      "=    O                              =",
      "=                                   =",
      "=                                   =",
      "====================================="
    ]
  },
  { id: 2,
    type: layerTypes.FLOOR,
    body: 
    [ "                                     ",
      "                                     ",
      "                                     ",
      "   R R R       T                     ",
      "                                     ",
      "   R R R       T T  MMMMMMMMMM       ",
      "                    MMMMMMMMMM       ",
      "         T   T T    MMMMMMMMMM       ",
      "                    MMMMMMMMMM       ",
      "       T T T T      MMMMMMM MM       ",
      "                    MMMMMMMMMM       ",
      "             T T                     ",
      "                                     ",
      "               T                     ",
      "                                     ",
      "                                     ",
      "                                     "
    ]
  },
  { id: 3,
    type: layerTypes.PRIMARY,
    body: 
    [ "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                     ==========      ",
      "                              =      ",
      "                    =         =      ",
      "                    =         =      ",
      "                    =         =      ",
      "             T      =         =      ",
      "                    ===========      ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     "
    ]
  },
  { id: 4,
    type: layerTypes.FLOOR,
    body: 
    [ "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     ",
      "                                     "
    ]
  }
]
