export const actionTypes = {
  CREATE_ERROR: 'CREATE_ERROR',
  RESET_MAP: 'RESET_MAP',

  ADD_TO_CELL: 'ADD_TO_CELL',
  REMOVE_FROM_CELL: 'REMOVE_FROM_CELL',

  CREATE_CREATURE: 'CREATE_CREATURE',
  UPDATE_CREATURE: 'UPDATE_CREATURE',
  CONTROL_CREATURE: 'CONTROL_CREATURE',
  SET_CURRENT_CREATURE: 'SET_CURRENT_CREATURE',
  SET_IS_FLYING: 'SET_IS_FLYING',
  DESTROY_OBJECT: 'DESTROY_OBJECT',
  MOVE_OBJECT: 'MOVE_OBJECT',

  CREATE_TERRAIN: 'CREATE_TERRAIN',

  ADVANCE_QUEUE: 'ADVANCE_QUEUE',
  REMOVE_NEXT_FROM_QUEUE: 'REMOVE_NEXT_FROM_QUEUE',

  MOVE: 'MOVE'
}
