export const CREATE_ERROR = 'CREATE_ERROR'

export const RESET_MAP = 'RESET_MAP'

export const ADD_TO_CELL = 'ADD_TO_CELL'
export const REMOVE_FROM_CELL = 'REMOVE_FROM_CELL'

export const CREATE_CREATURE = 'CREATE_CREATURE'
export const UPDATE_CREATURE = 'UPDATE_CREATURE'
export const CONTROL_CREATURE = 'CONTROL_CREATURE'
export const DESTROY_OBJECT = 'DESTROY_OBJECT'
export const MOVE_OBJECT = 'MOVE_OBJECT'

export const ADVANCE_QUEUE = 'ADVANCE_QUEUE'
export const REMOVE_NEXT_FROM_QUEUE = 'REMOVE_NEXT_FROM_QUEUE'

export const MOVE = 'MOVE'
