export const CREATE_ERROR = 'CREATE_ERROR'

export const RESET_MAP = 'RESET_MAP'

export const ADD_TO_CELL = 'ADD_TO_CELL'
export const REMOVE_FROM_CELL = 'REMOVE_FROM_CELL'

export const CREATE_CREATURE = 'CREATE_CREATURE'
export const UPDATE_CREATURE = 'UPDATE_CREATURE'
export const CONTROL_CREATURE = 'CONTROL_CREATURE'

export const MOVE = 'MOVE'
