import { directionTypes } from '../types'

let Keys = {
  ENTER: 'Enter',
  SPACE: ' ',
  W: 'w',
  S: 's',
  A: 'a',
  D: 'd',
  Q: 'q',
  E: 'e',
  R: 'r',
  K: 'k',
  J: 'j',
  PLUS: '+',
  MINUS: '-',
  UP: 'ArrowUp',
  DOWN: 'ArrowDown',
  LEFT: 'ArrowLeft',
  RIGHT: 'ArrowRight',
  NUMPAD1: '1',
  NUMPAD2: '2',
  NUMPAD3: '3',
  NUMPAD4: '4',
  NUMPAD5: '5',
  NUMPAD6: '6',
  NUMPAD7: '7',
  NUMPAD8: '8',
  NUMPAD9: '9',
}
let Keybinds = [
  [Keys.ENTER, {value: 'SELECT', tags: []}],
  [Keys.SPACE, {value: 'CHANGE', tags: []}],
  [Keys.K, {value: 'TOGGLE_FLY', tags: []}],
  [Keys.J, {value: 'JUMP_MODE', tags: []}],
  [Keys.R, {value: 'RESET', tags: []}],
  [Keys.W, {value: directionTypes.NORTH, tags: ['MOVE']}],
  [Keys.UP, {value: directionTypes.NORTH, tags: ['MOVE']}],
  [Keys.NUMPAD8, {value: directionTypes.NORTH, tags: ['MOVE']}],
  [Keys.NUMPAD9, {value: directionTypes.NORTHEAST, tags: ['MOVE']}],
  [Keys.D, {value: directionTypes.EAST, tags: ['MOVE']}],
  [Keys.RIGHT, {value: directionTypes.EAST, tags: ['MOVE']}],
  [Keys.NUMPAD6, {value: directionTypes.EAST, tags: ['MOVE']}],
  [Keys.NUMPAD3, {value: directionTypes.SOUTHEAST, tags: ['MOVE']}],
  [Keys.S, {value: directionTypes.SOUTH, tags: ['MOVE']}],
  [Keys.DOWN, {value: directionTypes.SOUTH, tags: ['MOVE']}],
  [Keys.NUMPAD2, {value: directionTypes.SOUTH, tags: ['MOVE']}],
  [Keys.NUMPAD1, {value: directionTypes.SOUTHWEST, tags: ['MOVE']}],
  [Keys.A, {value: directionTypes.WEST, tags: ['MOVE']}],
  [Keys.LEFT, {value: directionTypes.WEST, tags: ['MOVE']}],
  [Keys.NUMPAD4, {value: directionTypes.WEST, tags: ['MOVE']}],
  [Keys.NUMPAD7, {value: directionTypes.NORTHWEST, tags: ['MOVE']}],
  [Keys.NUMPAD5, {value: 'WAIT', tags: []}],
  [Keys.E, {value: directionTypes.UP, tags: ['MOVE']}],
  [Keys.Q, {value: directionTypes.DOWN, tags: ['MOVE']}],
  [Keys.PLUS, {value: directionTypes.UP, tags: ['MOVE']}],
  [Keys.MINUS, {value: directionTypes.DOWN, tags: ['MOVE']}]
]
Keybinds = new Map(Keybinds)


export default Keybinds
